export const products = [
  {
    id: "dog-food",
    name: "Hrană completă pentru câini adulți",
    details: "Rețetă echilibrată · 12 kg",
    price: 299.9,
    categories: ["Hrană", "Câini"],
    image: "/assets/product-dog-food.webp",
    rating: "4,9",
    reviews: 120,
    badge: "Preferatul blănoșilor",
    description: "O hrană completă pentru mesele de zi cu zi ale câinilor adulți. Pachetul de 12 kg este potrivit pentru familiile care vor să aibă hrana preferată mereu la îndemână.",
    highlights: ["Hrană completă pentru câini adulți", "Pachet generos de 12 kg", "Potrivită pentru mesele de zi cu zi"],
    specifications: [["Animal", "Câini"], ["Etapă de viață", "Adulți"], ["Cantitate", "12 kg"], ["Categorie", "Hrană uscată"]],
  },
  {
    id: "cat-food",
    name: "Hrană cu somon pentru pisici adulte",
    details: "Bobițe crocante · 1,5 kg",
    price: 64.9,
    categories: ["Hrană", "Pisici"],
    image: "/assets/product-cat-food.webp",
    rating: "4,8",
    reviews: 98,
    description: "Bobițe crocante cu somon, pregătite pentru mesele pisicilor adulte. Punga de 1,5 kg este ușor de păstrat la îndemână în fiecare zi.",
    highlights: ["Cu somon", "Pentru pisici adulte", "Pachet practic de 1,5 kg"],
    specifications: [["Animal", "Pisici"], ["Etapă de viață", "Adulte"], ["Cantitate", "1,5 kg"], ["Categorie", "Hrană uscată"]],
  },
  {
    id: "chicken-treats",
    name: "Bucățele fragede cu pui",
    details: "Recompense naturale · 80 g",
    price: 18.9,
    categories: ["Recompense", "Câini"],
    image: "/assets/product-treats.webp",
    rating: "4,9",
    reviews: 73,
    badge: "Ingredient simplu",
    description: "Bucățele fragede cu pui, numai bune pentru momentele de răsfăț și pentru a-ți recompensa companionul. Pachetul de 80 g încape ușor în geantă la plimbare.",
    highlights: ["Cu pui", "Textură fragedă", "Pachet ușor de luat la plimbare"],
    specifications: [["Animal", "Câini"], ["Tip", "Recompense"], ["Aromă", "Pui"], ["Cantitate", "80 g"]],
  },
  {
    id: "chew-toy",
    name: "Minge rezistentă pentru joacă",
    details: "Jucărie de cauciuc · mărimea M",
    price: 69.9,
    categories: ["Jucării", "Câini"],
    image: "/assets/product-toy.webp",
    rating: "4,8",
    reviews: 65,
    description: "O minge de cauciuc rezistentă pentru jocuri de aport și momente pline de energie. Mărimea M este ușor de prins și de adus înapoi.",
    highlights: ["Cauciuc rezistent", "Potrivită pentru jocuri de aport", "Mărimea M"],
    specifications: [["Animal", "Câini"], ["Tip", "Jucărie"], ["Material", "Cauciuc"], ["Mărime", "M"]],
  },
  {
    id: "knit-sweater",
    name: "Pulover moale pentru plimbări",
    details: "Tricot confortabil · mărimea S",
    price: 89.9,
    categories: ["Hăinuțe", "Câini"],
    image: "/assets/category-clothes.webp",
    rating: "4,7",
    reviews: 42,
    description: "Un pulover tricotat, moale și confortabil, pentru plimbările din zilele răcoroase. Modelul disponibil este mărimea S.",
    highlights: ["Tricot moale", "Pentru plimbări în zile răcoroase", "Mărimea S"],
    specifications: [["Animal", "Câini"], ["Tip", "Pulover"], ["Material", "Tricot"], ["Mărime", "S"]],
  },
];
